[book]
title = "The Erigon 3 Book"
authors = ["Erigon"]
description = "Erigon 3 documentation!"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/erigontech/docs"
