[book]
title = "Erigon 3 Docs"
authors = ["Erigon"]
description = "Erigon 3 documentation!"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/erigontech/docs"
[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
theme = "my-theme"
default-theme = "Ayu"
