name: Erigon Docs Deployment

on:
  push:
    branches:
      - development
      - main
      - testmichele

jobs:
  deploy-cloudflare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mdbook, linkchek and run build Book
        run: |
          # This assumes your book is in the root of your repository.
          # Just add a `cd` here if you need to change to another directory.
          cargo install mdbook
          cargo install mdbook-linkcheck
          mdbook build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy book --project-name=${{ secrets.CLOUDFLARE_PROJECT }} --commit-dirty=true